default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 500

development:
  <<: *default
  database: legit_research_development
  username: postgres

test:
  <<: *default
  database: legit_research_test
  username: postgres

production:
  <<: *default
  database: railway