default: &default
  adapter: postgresql
  encoding: unicode
  pool: 500
  url: postgresql://postgres:ogyYgHWnpIdVzwCagVQHafVjcSBlyxkf@viaduct.proxy.rlwy.net:38599/railway
  database: railway
  username: postgres
  password: ogyYgHWnpIdVzwCagVQHafVjcSBlyxkf
  host: viaduct.proxy.rlwy.net

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  
