default: &default
  adapter: postgresql
  encoding: unicode
  pool: 500

development:
  <<: *default
  database: ruby_rails_database_development
  username: postgres

test:
  <<: *default
  database: ruby_rails_database_test
  username: postgres

production:
  <<: *default
  url: postgresql://postgres:mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd@viaduct.proxy.rlwy.net:12609/railway
  database: railway
  username: postgres
  password: mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd
  host: viaduct.proxy.rlwy.net
  port: 12609
