default: &default
  adapter: postgresql
  encoding: unicode
  pool: 500
  url: postgresql://postgres:yJtNcatyVHQmdHWkYMIoqNDkaVSMnIGz@monorail.proxy.rlwy.net:27324/railway
  database: railway
  username: postgres
  password: yJtNcatyVHQmdHWkYMIoqNDkaVSMnIGz
  host: monorail.proxy.rlwy.net

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
