default: &default
  adapter: postgresql
  encoding: unicode
  pool: 500

development:
  <<: *default
  database: ruby_rails_database_development
  username: postgres

test:
  <<: *default
  database: ruby_rails_database_test
  username: postgres

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
