default: &default
  adapter: postgresql
  encoding: unicode
  pool: 500

development:
  <<: *default
  url: postgresql://postgres:mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd@viaduct.proxy.rlwy.net:12609/railway
  database: railway
  username: postgres
  password: mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd
  host: viaduct.proxy.rlwy.net

test:
  <<: *default
  url: postgresql://postgres:mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd@viaduct.proxy.rlwy.net:12609/railway
  database: railway
  username: postgres
  password: mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd
  host: viaduct.proxy.rlwy.net

production:
  <<: *default
  url: postgresql://postgres:mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd@viaduct.proxy.rlwy.net:12609/railway
  database: railway
  username: postgres
  password: mPTQueYcuCTcOgdcKVzAbELUNwYZdpDd
  host: viaduct.proxy.rlwy.net
